// <auto-generated />
using System;
using DACN_CNPM_QuanLyXayDung.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACN_CNPM_QuanLyXayDung.Migrations
{
    [DbContext(typeof(HeThongQlvongDoiDuAnTaiNguyenContext))]
    [Migration("20260414133124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WarehouseKeeperId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("WarehouseKeeperID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Inventor__55433A4B41C394E1");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageId");

                    b.HasIndex("WarehouseKeeperId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MinStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Material__C506131779539DC7");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.MaterialUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<int>("QuantityUsage")
                        .HasColumnType("int");

                    b.HasKey("UsageId")
                        .HasName("PK__Material__29B197C0B1BF7FD0");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectId");

                    b.ToTable("MaterialUsage", (string)null);
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelatedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<bool>("BudgetLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("ContractFileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContractFileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ContractUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ManagerID");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Planned");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABED0C1B18240");

                    b.HasIndex("ManagerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3AB04EA8A4");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AssignedUserID");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<bool>("BudgetLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MaterialDeclarationContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("MaterialDeclarationFileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MaterialDeclarationFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("MaterialDeclarationUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Planned");

                    b.HasKey("StageId")
                        .HasName("PK__Stages__03EB7AF8309468FE");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<int>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949D13E927275");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC6598EAF8");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__A9D10534D8332783")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.InventoryTransaction", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Material", "Material")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Material");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Project", "Project")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Inventory_Project");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Stage", "Stage")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("StageId")
                        .HasConstraintName("FK_Inventory_Stage");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.User", "WarehouseKeeper")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseKeeperId")
                        .HasConstraintName("FK_Inventory_User");

                    b.Navigation("Material");

                    b.Navigation("Project");

                    b.Navigation("Stage");

                    b.Navigation("WarehouseKeeper");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.MaterialUsage", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Material", "Material")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_Usage_Material");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Project", "Project")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Usage_Project");

                    b.Navigation("Material");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Notification", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Project", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.User", "Manager")
                        .WithMany("Projects")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Projects_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Stage", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.User", "AssignedUser")
                        .WithMany("Stages")
                        .HasForeignKey("AssignedUserId")
                        .HasConstraintName("FK_Stages_User");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Project", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Stages_Project");

                    b.Navigation("AssignedUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Task", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Tasks_Project");

                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Stage", "Stage")
                        .WithMany("Tasks")
                        .HasForeignKey("StageId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Stage");

                    b.Navigation("Project");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.User", b =>
                {
                    b.HasOne("DACN_CNPM_QuanLyXayDung.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__571DF1D5");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Material", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("MaterialUsages");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Project", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("MaterialUsages");

                    b.Navigation("Stages");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.Stage", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DACN_CNPM_QuanLyXayDung.Models.User", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Projects");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
